#hwdec=vaapi,auto
hwdec=vaapi,vulkan-copy,auto
vo=gpu-next
#profile=high-quality
#gpu-api=vulkan
#gpu-context=auto
#scale=ewa_lanczossharp
#cscale=ewa_lanczossharp
#video-sync=display-resample
#interpolation
#tscale=oversample
volume-max=200

# --- uosc setup ---
osc=no
osd-bar=no
border=no
save-position-on-quit=yes
watch-later-options=start,speed,volume
script-opts=uosc-font_scale=1.25
