apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-driver
  namespace: default
  labels:
    io.kompose.service: tds-notebooks
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "nodes", "services", "persistentvolumeclaims", "configmaps"]
  verbs: ["get", "watch", "list", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-driver
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: spark-driver
  apiGroup: rbac.authorization.k8s.io
