Gdk/UnscaledDPI 98304
Gdk/WindowScalingFactor 1
Gtk/EnableAnimations 1
Gtk/DecorationLayout "close,maximize,minimize:"
Net/ThemeName "Breeze-Dark"
Gtk/PrimaryButtonWarpsSlider 1
Gtk/ToolbarStyle 3
Gtk/MenuImages 1
Gtk/ButtonImages 1
Net/CursorBlinkTime 1000
Net/CursorBlink 1
Gtk/CursorThemeSize 30
Gtk/CursorThemeName "Catppuccin-Macchiato-Flamingo-Cursors"
Net/SoundThemeName "ocean"
Net/IconThemeName "Catppuccin-Mocha-Alt2"
Gtk/FontName "Ubuntu Sans,  13"
